import { describe } from "node:test";
import { title } from "process";

export const sliderPortfolioData = [
  {
    topInfo: {
      location: "USA",
      date: "May 1, 2024",
      createBy: "bboyswirv & kianadaigneault",
      igUrl: "https://www.instagram.com/bboyswirv/",
    },
    categories: "Starwars",
    videoThum: "/assets/home/starwars-thum.png",
    videoUrl: "/assets/video/starwars-thum.mp4",
    title: "Double Blade",
    subTitle: "Lightsaber vs Blaster Fight",
    descriptionOne: `During Star Wars Week, we showcased an epic duel featuring a double-bladed lightsaber versus blasters! Thanks to Kiana Daigneault, David Hernandez, Bboy Swirv, Cosplay Powers, and This Guy's Audio for the thrilling visuals and sound. Our video hit 73,000+ views—check out @byolightsaber for your own galactic gear!
`,
  },

  {
    topInfo: {
      location: "USA",
      date: "July 28, 2022",
      createBy: "Laneyfeni",
      igUrl: "https://www.instagram.com/laneyfeni/",
    },
    categories: "Marvel",
    videoThum: "/assets/home/marvel-thum.png",
    videoUrl: "/assets/video/marvel-thum.mp4",
    title: "Thorsday",
    descriptionOne: `I had the pleasure of collaborating with the talented Laney Feni on a dynamic VFX edit for Thor, which showcased our combined creative vision and expertise. The project reached over 109,000 people, bringing Thor's thunderous energy to life with stunning visuals and effects.`,
  },

  {
    topInfo: {
      location: "USA",
      date: "August 23, 2023",
      createBy: "sirjuliuscosplay",
      igUrl: "https://www.instagram.com/sirjuliuscosplay/",
    },
    categories: "DC",
    videoThum: "/assets/home/dc-thum.png",
    videoUrl: "/assets/video/dc-thum.mp4",
    title: "Blue Beetle",
    descriptionOne: `Check out the incredible Blue Beetle VFX we created in just 24 hours for @sirjuliuscosplay! Imagine what we could do in a month—his Blue Beetle is seriously amazing! If you're in need of some top-tier VFX, hit us up! Stay tuned for more!`,

    descriptionTwo: `Blue Beetle 🪲 @sirjuliuscosplay VFX by @cosplaypowers —— Stats: 18,000+ reached`,
  },

  {
    topInfo: {
      location: "USA",
      date: "April 7, 2024",
      createBy: "renzorage",
      igUrl: "https://www.instagram.com/renzorage/",
    },
    categories: "Avatar",
    videoThum: "/assets/home/avatar-thum.png",
    videoUrl: "/assets/video/avatar-thum.mp4",
    title: "Fire Bending",
    descriptionOne: `Check out this incredible fire-bending VFX we created for Renzorage using Trapcode Elements. We collaborated with Zack from CGVisuals for the stunning visual effects and This Guy's Audio for the immersive sound design. The project reached over 217,000 people, showcasing the power of dynamic VFX and audio teamwork!`,
  },

  {
    topInfo: {
      location: "USA",
      date: "October 10, 2023",
      createBy: "Ash-Lee Entertainment",
      igUrl: "https://www.instagram.com/ashleeentertainment/",
    },
    categories: "TMNT",
    videoThum: "/assets/home/tmnt-thum.png",
    videoUrl: "/assets/video/tmnt-thum.mp4",
    title: "Michelangelo",
    descriptionOne: `You might want to be careful when walking the streets of New York – you never know what could be lurking beneath, waving hello to you! 🤣 This fun moment featuring Michelangelo was captured during my collaboration with @ashleeentertainment, and it reached over 35,000 people.`,
  },

  {
    topInfo: {
      location: "USA",
      date: "September 5, 2022",
      createBy: "Hellspawned_Cosplay",
      igUrl: "https://www.instagram.com/hellspawned_cosplay/",
    },
    categories: "Marvel",
    videoThum: "/assets/home/marvel-thum 2.png",
    videoUrl: "/assets/video/marvel-thum2.mp4",
    title: "Optic Blast!",
    descriptionOne: `Cyclops Optic Blast 💥 – As part of a dynamic collaboration with cosplayer @hellspawned_cosplay, this project showcased stunning visual effects that captured the iconic power of Cyclops. With over 45,000 people reached, this video brought the character to life through expertly crafted VFX and engaging cosplay performance.`,
  },
];

export const gallerySilderData = [
  { url: "/assets/gallery-img/gallery-img-1.png" },
  { url: "/assets/gallery-img/gallery-img-2.png" },
  { url: "/assets/gallery-img/gallery-img-3.png" },
  { url: "/assets/gallery-img/gallery-img-4.png" },
  { url: "/assets/gallery-img/gallery-img-5.png" },
  { url: "/assets/gallery-img/gallery-img-6.png" },
  { url: "/assets/gallery-img/gallery-img-7.png" },
  { url: "/assets/gallery-img/gallery-img-8.png" },
  { url: "/assets/gallery-img/gallery-img-9.png" },
  { url: "/assets/gallery-img/gallery-img-10.png" },
  { url: "/assets/gallery-img/gallery-img-11.png" },
  { url: "/assets/gallery-img/gallery-img-12.png" },
  { url: "/assets/gallery-img/gallery-img-13.png" },
  { url: "/assets/gallery-img/gallery-img-14.png" },
  { url: "/assets/gallery-img/gallery-img-15.png" },
  { url: "/assets/gallery-img/gallery-img-16.png" },
  { url: "/assets/gallery-img/gallery-img-17.png" },
  { url: "/assets/gallery-img/gallery-img-18.png" },
  { url: "/assets/gallery-img/gallery-img-19.png" },
  { url: "/assets/gallery-img/gallery-img-20.png" },
  { url: "/assets/gallery-img/gallery-img-21.png" },
  { url: "/assets/gallery-img/gallery-img-22.png" },
  { url: "/assets/gallery-img/gallery-img-23.png" },
  { url: "/assets/gallery-img/gallery-img-24.png" },
  { url: "/assets/gallery-img/gallery-img-25.png" },
  { url: "/assets/gallery-img/gallery-img-26.png" },
  { url: "/assets/gallery-img/gallery-img-27.png" },
  { url: "/assets/gallery-img/gallery-img-28.png" },
  { url: "/assets/gallery-img/gallery-img-29.png" },
  { url: "/assets/gallery-img/gallery-img-30.png" },
  { url: "/assets/gallery-img/gallery-img-31.png" },
  { url: "/assets/gallery-img/gallery-img-32.png" },
  { url: "/assets/gallery-img/gallery-img-33.png" },
  { url: "/assets/gallery-img/gallery-img-34.png" },
  { url: "/assets/gallery-img/gallery-img-35.png" },
  { url: "/assets/gallery-img/gallery-img-36.png" },
  { url: "/assets/gallery-img/gallery-img-37.png" },
  { url: "/assets/gallery-img/gallery-img-38.png" },
  { url: "/assets/gallery-img/gallery-img-39.png" },
  { url: "/assets/gallery-img/gallery-img-40.png" },
  { url: "/assets/gallery-img/gallery-img-41.png" },
  { url: "/assets/gallery-img/gallery-img-42.png" },
  { url: "/assets/gallery-img/gallery-img-43.png" },
  { url: "/assets/gallery-img/gallery-img-44.png" },
  { url: "/assets/gallery-img/gallery-img-45.png" },
  { url: "/assets/gallery-img/gallery-img-46.png" },
  { url: "/assets/gallery-img/gallery-img-47.png" },
  { url: "/assets/gallery-img/gallery-img-48.png" },
  { url: "/assets/gallery-img/gallery-img-49.png" },
  { url: "/assets/gallery-img/gallery-img-50.png" },
  { url: "/assets/gallery-img/gallery-img-51.png" },
  { url: "/assets/gallery-img/gallery-img-52.png" },
  { url: "/assets/gallery-img/gallery-img-53.png" },
  { url: "/assets/gallery-img/gallery-img-54.png" },
  { url: "/assets/gallery-img/gallery-img-55.png" },
  { url: "/assets/gallery-img/gallery-img-56.png" },
  { url: "/assets/gallery-img/gallery-img-57.png" },
  { url: "/assets/gallery-img/gallery-img-58.png" },
  { url: "/assets/gallery-img/gallery-img-59.png" },
  { url: "/assets/gallery-img/gallery-img-60.png" },
  { url: "/assets/gallery-img/gallery-img-61.png" },
  { url: "/assets/gallery-img/gallery-img-62.png" },
  { url: "/assets/gallery-img/gallery-img-63.png" },
  { url: "/assets/gallery-img/gallery-img-64.png" },
  { url: "/assets/gallery-img/gallery-img-65.png" },
  { url: "/assets/gallery-img/gallery-img-66.png" },
  { url: "/assets/gallery-img/gallery-img-67.png" },
  { url: "/assets/gallery-img/gallery-img-68.png" },
  { url: "/assets/gallery-img/gallery-img-69.png" },
  { url: "/assets/gallery-img/gallery-img-70.png" },
  { url: "/assets/gallery-img/gallery-img-71.png" },
  { url: "/assets/gallery-img/gallery-img-72.png" },
  { url: "/assets/gallery-img/gallery-img-73.png" },
  { url: "/assets/gallery-img/gallery-img-74.png" },
  { url: "/assets/gallery-img/gallery-img-75.png" },
  { url: "/assets/gallery-img/gallery-img-76.png" },
  { url: "/assets/gallery-img/gallery-img-77.png" },
  { url: "/assets/gallery-img/gallery-img-78.png" },
];
